image: "docker:18"
services:
  - docker:dind

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/svenstaro/bankthing:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/svenstaro/bankthing:latest

stages:
  - build
  - test
  - release
  - deploy

build-image:
  stage: build
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  script:
    - docker pull $CONTAINER_TEST_IMAGE || true
    - docker build --cache-from $CONTAINER_TEST_IMAGE -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test:
  stage: test
  image:
    name: $CONTAINER_TEST_IMAGE
    entrypoint: [""]
  services:
    - postgres:10
  script:
    - pytest

release-image:
  stage: release
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

deploy:
  stage: deploy
  image: python:3.6-stretch
  script:
    - pip install ansible
